# Programación 201

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [1]:
# Librería:
import numpy as np

In [2]:
Matriz = [[1, 0], [2, -1]]
print(f"La norma de la matriz es: {np.linalg.norm(Matriz)}")
print(f"El determinante : {np.linalg.det(Matriz)}")

La norma de la matriz es: 2.449489742783178
El determinante : -1.0


### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [3]:
arcoseno= np.arcsin(np.arange(0,1,0.1)) # Numeros entre 0 y 1 a intervalos de 0.1
arcocoseno = np.arccos(np.arange(0,1,0.1))
print(f"  Arcoseno: \n {arcoseno}")
print(f"  Arcocoseno: \n {arcocoseno}")

  Arcoseno: 
 [0.         0.10016742 0.20135792 0.30469265 0.41151685 0.52359878
 0.64350111 0.7753975  0.92729522 1.11976951]
  Arcocoseno: 
 [1.57079633 1.47062891 1.36943841 1.26610367 1.15927948 1.04719755
 0.92729522 0.79539883 0.64350111 0.45102681]


### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [4]:
# Lista de valores enteros:
Ej3 = list(np.random.randint(0,9, 100))

print(f" Media de la lista: {np.mean(Ej3)}")
print(f" La desviación estándar de los valore de la lista: {np.std(Ej3)}")
print(f" Valor Máximo de la lista: {np.max(Ej3)}")
print(f" Valor Mínimo de la lista: {np.min(Ej3)}")
print(f" Suma de los valores: {np.sum(Ej3)}")
print(f" Valores únicos: {np.unique(Ej3)}")

#np.linspace(0,9,100) # genera un array NumPy formado por n números equiespaciados entre dos dados.

 Media de la lista: 3.9
 La desviación estándar de los valore de la lista: 2.6702059845637374
 Valor Máximo de la lista: 8
 Valor Mínimo de la lista: 0
 Suma de los valores: 390
 Valores únicos: [0 1 2 3 4 5 6 7 8]


### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [5]:
# Creo la Matriz
Ej4 = np.array([[5,1,7], [0,7,4], [7,23,1]])
print(f" Matriz: \n {Ej4}")
Ej4_ordenada = np.sort(Ej4, axis = 0, kind = "mergesort")
print(f"Matriz ordenada por filas utilizando el metodo 'Mergesort' \n {Ej4_ordenada}")

 Matriz: 
 [[ 5  1  7]
 [ 0  7  4]
 [ 7 23  1]]
Matriz ordenada por filas utilizando el metodo 'Mergesort' 
 [[ 0  1  1]
 [ 5  7  4]
 [ 7 23  7]]


 - ["Numpy_Sort"](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sort.html)

### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [6]:
# Creamos dos matrices
M1 = np.random.random((2,2))
M2 = np.random.random((2,2))
# Funcion que devolvera el valor absoluto(abs) de la multiplicacion de los determinantes
def multiplicacion_determinantes(M1,M2):
    resultado = np.abs(np.linalg.det(M1)*np.linalg.det(M2))
    print (resultado)
    
multiplicacion_determinantes(M1,M2)

0.1897859394976781


### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [7]:
M_identidad = np.identity(10)
M_identidad
# La primera matriz la creo manual? o puedo hacer un for?

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# Comprobación:
#(M_identidad == b).all()

### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [8]:
# Creo una matriz 2 x 6 de tipo enteros
Ej7 = np.arange(0,12, dtype=int).reshape((2,6))
# con numpy.reshape: podemos añadir, eliminar dimensiones o cambiar el número de elementos en cada dim
Ej7

row = Ej7.shape[0]
cols = Ej7.shape[1]

for x in range(0,row):
    for y in range(0,cols):
        if x%2 == 0:
            Ej7[x][y] = x^2+y
        else:
            try: 
                Ej7[x][y] = x/(y^2)
            except ZeroDivisionError:
                Ej7[x][y] = 0

Ej7

array([[2, 3, 4, 5, 6, 7],
       [0, 0, 0, 1, 0, 0]])

### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [9]:
# Creación matrices de tamaño 5 x 5 no números reales aleatorios
a = np.random.rand(5,5)
b = np.random.rand(5,5)

print(f"Multiplicación elemento por elemento: \n {a*b}") # Multiplicacion elemento por elemento
print(f"Multiplicación de una Matriz por Otra: \n {a.dot(b)}") #Multiplición de una matriz por otra

Multiplicación elemento por elemento: 
 [[0.3390947  0.2615773  0.24952968 0.12035363 0.04193841]
 [0.00925951 0.07290119 0.05698608 0.06797149 0.79855461]
 [0.37595047 0.26935264 0.94876645 0.09214216 0.61719526]
 [0.11300217 0.7106408  0.06252515 0.110301   0.13166307]
 [0.86168903 0.29029245 0.22193428 0.01290139 0.27146569]]
Multiplicación de una Matriz por Otra: 
 [[0.94217956 1.24346989 0.92928238 1.10821633 1.13055046]
 [1.24073683 0.87297044 0.84422999 1.13138906 1.14158499]
 [1.86218845 1.7845598  1.73616907 1.52419471 1.88647859]
 [1.20022165 1.15198933 1.15294021 1.52497478 1.58534306]
 [1.4444867  1.35455229 1.40002561 1.39541676 1.751641  ]]


In [11]:
# Creación matrices de tamaño 4 x 5 y 5 x 5
a = np.random.rand(4,5)
print(f"Matriz 'a': {a.shape}") # Nos devolverá la dimensión o el tamaño

b = np.random.rand(5,5)
print(f"Matriz 'b': {a.shape}") 

# Aplicando producto matricial:
print(f"Multiplicación de una Matriz por Otra: \n {a.dot(b)}") 
# Producto tensorial (estaría multiplicando coordenadas por lo que al no encontrar una de ella genera error)
print(f"Multiplicación elemento por elemento: \n {a*b}")  # Cuando multiplicamos matrices de diferentes dimensiones se produce un error

Matriz 'a': (4, 5)
Matriz 'b': (4, 5)
Multiplicación de una Matriz por Otra: 
 [[0.95017838 1.21335427 1.77551682 1.14606549 1.16712483]
 [0.62050606 1.08631926 1.39782279 0.98570891 1.27482183]
 [1.06748634 1.52948986 1.98136024 1.44956728 1.35051434]
 [0.76910731 0.94836572 1.66369218 1.37160997 1.11334677]]


ValueError: operands could not be broadcast together with shapes (4,5) (5,5) 

 [Producto de Matrices - MUY BASICO](https://ekuatio.com/como-multiplicar-matrices/)
" Para multiplicar dos matrices, se debe cumplir una condición muy importante:
El número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz"